### ISSUE TITLE
各种云函数和数据库的表都建好安装完依赖并上传，为什么请求不到数据？

### ISSUE THREAD

**Issue by hanzehua666** [GoKu-gaga/today#1]
![image](https://user-images.githubusercontent.com/30396590/53536929-27e9eb80-3b43-11e9-9b55-6f3c69fc7415.png)
![image](https://user-images.githubusercontent.com/30396590/53538515-faa03c00-3b48-11e9-9758-7209a24c86fb.png)
聚合接口的数据接口我单独调的数据是有的

**Comment by GoKu-gaga** [comment]
这个可以在云开发控制台 -> 云函数 -> 查看日志找找哪里出错了哦

**Comment by yuanyican** [comment]
@hanzehua666   
- 可以在云开发控制台 -> 云函数 -> 查看日志
- 记得删除云数据库的错误记录再进行debug
理论上只要config.js里两个字段正确，就没问题的。
